language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install sklearn scipy numpy numba pandas joblib

script:
  - make clean
  - make
  - python -m unittest discover

branches:
  only:
    - master