language: python

python:
  - 2.7
  - 3.5
  - 3.6

install:
  - pip install sklearn scipy numpy numba pandas joblib

script:
  - make clean -C citrees
  - make -C citrees/
  - python -m unittest discover

branches:
  only:
    - master